name: yegna_budget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  percent_indicator: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  share_plus: ^12.0.1
  abushakir: ^1.0.0
  lottie: ^3.3.2
  image_picker: ^1.0.7
  pdf: ^3.10.7
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  open_filex: ^4.0.0
  rename_app: ^1.6.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/financial_tips.json
    - assets/images/buffer_tip.png
    - assets/images/spending_chart.png
    - assets/images/logo.png
    - assets/lottie/Success.json
    - assets/lottie/wrong.json
    - assets/icons/
    - assets/icons/apps.svg
    - assets/icons/budget.svg
    - assets/icons/caleder_today.svg
    - assets/icons/coffee.svg
    - assets/icons/credit_card.svg
    - assets/icons/emergency.svg
    - assets/icons/emoji_events.svg
    - assets/icons/envelope.svg
    - assets/icons/event.svg
    - assets/icons/flag.svg
    - assets/icons/meal.svg
    - assets/icons/pie_chart.svg
    - assets/icons/savings.svg
    - assets/icons/shopping_card.svg
    - assets/icons/lightbulb.svg
    - assets/images/developer.jpg
    - assets/icons/instagram.svg
    - assets/icons/whatsapp.svg
    - assets/icons/telegramlogo.svg
