name: yegna_budget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  percent_indicator: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  share_plus: ^7.2.2
  abushakir: ^1.0.0
  lottie: ^2.7.0
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/financial_tips.json
    - assets/images/buffer_tip.png
    - assets/images/spending_chart.png
    - assets/images/monthly_review.png
    - assets/lottie/Success.json
    - assets/lottie/wrong.json

   